author: Xin Ge
title: Xin Ge's Blog
description: To record technical notes 
avatar: https://github.com/gexin1023.png?size=140


# Includes an icon in the footer for each username you enter
#footer-links:
dribbble:
email: gexin1023@gmail.com
facebook:
flickr:
github_username: gexin1023
instagram:
linkedin:
pinterest:
rss: feed # just type anything here for a working RSS icon
twitter_username: gexin1023
stackoverflow: # your stackoverflow profile, e.g. "users/50476/bart-kiers"
youtube: # channel/<your_long_string> or user/<user-name>
googleplus: # anything in your profile username that comes after plus.google.com/


disqus_id: gexin1023

# Enter your Google Analytics web tracking code (e.g. UA-2110908-2) to activate tracking
#google_analytics:

# Your website URL (e.g. http://barryclark.github.io or http://www.barryclark.co)
# Used for Sitemap.xml and your RSS feed
url: https://gexin1023.github.io

# If you're hosting your site at a Project repository on GitHub pages
# (http://yourusername.github.io/repository-name)
# and NOT your User repository (http://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"
baseurl:

#
# !! You don't need to change any of the configuration flags below !!
#

permalink: /:year/:month/:title.html

# The release of Jekyll Now that you're using
version: v3.1.6

include: [_pages]

markdown: kramdown
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge
  syntax_highlighter_opts:
  css_class: 'highlight'
  parse_block_html: true
  toc_levels: 1..3


# Set the Sass partials directory, as we're using @imports
sass:
  style: :expanded # You might prefer to minify using :compressed

# Use the following plug-ins
plugins-dir:
 - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem
 - jekyll-feed # Create an Atom feed using the official Jekyll feed gem
 # - jekyll-gist
 - jekyll-toc

# Exclude these files from your production _site
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME
  - Rakefile
  - favicon.ico

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      category: "main"
